document.write("	<!-- Navbar -->");
document.write("	<header class=\"navbar navbar-expand-md bg-dark navbar-dark\">");
document.write("	");
document.write("		<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">");
document.write("			<span class=\"navbar-toggler-icon\"><\/span>");
document.write("		<\/button>");
document.write("		");
document.write("		<div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">");
document.write("			<ul class=\"navbar-nav\">");
document.write("				<li class=\"nav-item\">");
document.write("					<a class=\"nav-link\" href=\"\">Home<\/a>");
document.write("				<\/li>");
document.write("				<li class=\"nav-item\">");
document.write("					<a class=\"nav-link\" href=\"#\">Info<\/a>");
document.write("				<\/li>");
document.write("				<li class=\"nav-item\">");
document.write("					<a class=\"nav-link\" href=\"#\">Music<\/a>");
document.write("				<\/li>");
document.write("				<li class=\"nav-item\">");
document.write("					<a class=\"nav-link\" href=\"#\">Forum<\/a>");
document.write("				<\/li>");
document.write("				<li class=\"nav-item\">");
document.write("					<a class=\"nav-link\" href=\"#\">Contact<\/a>");
document.write("				<\/li>");
document.write("			<\/ul>");
document.write("		<\/div>");
document.write("		");
document.write("	<\/header>");
document.write("	");
document.write("	<!-- Banner -->");
document.write("	 <div class=\"jumbotron text-center\">");
document.write("		<h1>Samiser<\/h1>");
document.write("	<\/div>");
